apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
    #namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-secretstore
    kind: SecretStore
  target:
    name: app-secrets-vault # Kubernetes secret name
  data:
  - secretKey: MYSQL_ROOT_PASSWORD # This will be the key in the Kubernetes secret.
    remoteRef: 
      key: weather-app/data/app-secrets # Path of the secret in Vault (KV-v2 path).
      property: MYSQL_ROOT_PASSWORD     # The specific key from the secret in Vault.
  - secretKey: MYSQL_PASSWORD
    remoteRef: 
      key: weather-app/data/app-secrets
      property: MYSQL_PASSWORD
  - secretKey: APIKEY
    remoteRef: 
      key: weather-app/data/app-secrets
      property: APIKEY
  - secretKey: DB_PASSWORD
    remoteRef: 
      key: weather-app/data/app-secrets
      property: DB_PASSWORD
  - secretKey: REDIS_PASSWORD
    remoteRef: 
      key: weather-app/data/app-secrets
      property: REDIS_PASSWORD
