apiVersion: external-secrets.io/v1beta1
kind: SecretStore # This one can be ClusterSecretStore for a cluster lavel resources 
metadata:
  name: vault-backend-secretstore
  #namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://172.25.11.223:8200" # "http://vault.vault.svc.cluster.local:8200" # Calling local vault running in same cluster
      path: "weather-app"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "67bc33f6-aad6-495d-205c-254d96dc38fe"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
