---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-secret
  namespace: default
spec:
  encryptedData:
    secret-id: AgCvkk7btnYPdz4c4TL7u/R4LdZFFjJB57WW5jySH90XPPudOiGioedW2lGFbLBpHOK5Atlxr4IP0OwIZuEN1VlDAiZOwzeFQFA/8VsZJg4oEsVolnXDhP33CnysKUzLnRW62760WuHbOQWX7JBJ3+0/EhrUd2s50RACgu3oMLz8d7Sb6pBoTKDhZEqy/ZfHk2nGthMHgxMZhyhHwWtcnCAfvnYyP8pkKYAzAIuLS7zr8TSW/9z/MJHYNDxxVWBcKlg4KB43t/6RV/U+QUTqK2Ge/flDjPuORFHvK/NGETGMDWsGEnZB7Bcwkfs9mg5kdyRHwcKSinlp1WlSnXg8MFC8jUoTb2UslWV4v8S3kX4hRca0/ZjrsAnjd/64l+g6SXqrpX6RUbekg90+uWs/ZmJ9DiCJwAQ3zWwqm/Z3rAdDh0vnxZPdYetimaaTQNYZz0zq2RUo9ytTgID4EW1T+3eoco+myukL9Sw2BJT13vjZhICgP+Rrr34+sg8ZOWC92Ilpdp5Kd5VezGqS6WmMCrRkvfoSdSTzaeb+jvQxFTwOTFAZUOSEzpECovm0fi+Tg1kY1FBzKgsgIchqCN4d9QssEhgHt1MRxNKXiDiYwah6KLG1C5j5zfe4XxbU+bdJ2P6Tnd4hFBfhpKOjdZn+QcJ6Lx/KdWvpObvZUOUkk18fmDeJlHBvPwJ5KDB7edzxH6sZ3GKMqpPzy/D8LQnIkS/ll5RurIdZ0lHITqrS379dUvMu8F4=
  template:
    metadata:
      creationTimestamp: null
      name: vault-secret
      namespace: default
    type: Opaque
