---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-secret
  namespace: default
spec:
  encryptedData:
    secret-id: AgCI1BedgUhwNo7u0NcEK+6iGQ12jTuYpTWqnWiA7z3+eJiDInMlfT5IKJqpDkzsmf2CPmKdwnhF4A72X6yJTtZDZlevwRXXbAcXt0vi83/imwNa8wCMjZHQ8D5bGJr3X44VF5SCpfEp/Np2rpQlV7Tp0JW2SUme0ur7B5sn+SA6aBqp1GMELyaVi+q6vHmxEIgePwLITlg9DFdMpR6RNQ1+1gTc8puygCzsU262drnUioTirNvgJ0ucLID74ByeNdZWNG0+J+YSrzZLTpmo2HfrD0osyMUdJ9XurFhPQ8RtcPg12g9hITBjpoWy84PVoF4U/Cy9elWwvyt6d7JRt+F7JSoqouLNfgKpMXWV78jw+DGLTQtPUtf9iEepHCJtzbuNl0dIaTMy1gKs9u0x97Rwof4N+g0PCRxu2I/T9RBO3P/Gmx/p8z+acmTWi84WBulwiIvtePVks5oni8xyrfxtp7zV97+0pz8zAWqFf9kRc3QtRozx2kq0UdbQ8n54CNDZ+IYQslVUzzFD3zNlx9xGIakifpZgWSjEUebW2ruHcrcQS3oJnev2CUnRMIIa3sM7UMBI59ZzywquVt6+6akK41llILwkECYSdhB0+L0DYKkWZmgTlvPxgiJ/5RpCPHQeD8huPAJTQCz2dpcnrj67oPS1/WdhgH8mYFqPOb9lFU2KzFSaf+Zv/KAaFSwGT+49GwEJe54P8ZdSZ8E/ygb8O1KQaTP+Inw/+mlO/RrU2JkturQ=
  template:
    metadata:
      creationTimestamp: null
      name: vault-secret
      namespace: default
    type: Opaque
