apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
type: Opaque
data:
  access-key: JKHbf54DE8s2RjKGFo8Pjfu3g8HR=  # Base64-encoded Access Key ID
  secret-access-key: LOI98jhruFRE54G0L2plOPMH5KH39GTDghdlFDqTQZmo0jUDQP5d8Tg==
