---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: awssm-secret
  namespace: default
spec:
  encryptedData:
    access-key: AgC0xNj8/QqiTocS3D83ml1JMl/A1IeqMPKxDxxeTaMUV+sx2y2KEhPVrIjABYJqHPWDmubPJ6+rOVt16l+hMeqdn4J/t0kNPG8nKTYt9eIyUvz4PoFIe4o5ZaQRkx5K1wInR6KS5W6l3pXbt+/bt8ZfCfms8gM8XkaPxuDY0L9h6SyDPl7DB9tYUfzFO3HUZHJzM6E982OAQco4W9d2SURhp1Dpsn9YiNtOrZIIEdoGAkC2AiXJmBLzKxivIGUGNfR0F6SOps69iSLx37yVz1skOB/hL55ePfT76QUDpWicfp+5AkjlzRxcSqrVXZHlIZ1dWRF+mLrkldpGYEeUl7C02dwkhUvmZt05TQNW6pgccMETRE+ZK4lzbqA3/Z78c2nKzwa2fIhp6Yae+HJg1mMBTwB16tJPGWMSVifoi8UJGG5hQu+AX4Wg7hoRGr85JBHTMUbSgiUU50Q1z1GpMI8AEcWexbd9SxgnPEH3wSoi/FdNCDvNtZ0lyJuO+iREvHjIgt1z3bierQWWZ9DcyHzS48+wISfljJbqpFUWpVTLJsrPWStrHL2zhwyEIeYrfZJ7AQ9yx4ro8ww9S57tEUmaLbkBjbhbFevPSm3W6sOXSAcNdrh9UuY4vkrxh9YpAxIfkBGI9nXQ/Y7bFIuESe6yAfjsJN2ActlmKcBS+lcyPOcXqQQNoFpqA5ZfHoOlRPQMoJrtTXzi9RkAsHDkH8pI1lCBRA==
    secret-access-key: AgAZ4Lsov1e0+771nL8Q5HOE+yeVVXzhk4pFVaYQhdPAhWv2zLQxof5prYcO+gJ+TT7sw994Er76RVC0Tk9PSAus5igKdj/W51IpBAuCm+nnROR1Sor7L0efKvgfoyDEyNEqeGVDdVI913qOBvwqN6UABD6WiESWQcNCBON9Kai3UWItfIN0F7yFtR346o5t+VmpoOISqCrGHLx/jnxmLkNujQ8u2He0VoCN5rLe8bg7E1fvSHJqjVuJSdvTUcQyaKd7YaUnEUuweb3dKADAyYQe8uOMnoeEB8D6E2xBZcLoB0rkRYI8/MwaykaEPTCCcBLo7pgNGfOB6ZYrTN9GdouJ55d5h6B3dflDfYbalh8pnK9O3UHlNrafpv7+9BRu2p8D6b1V8UeQIJFtuLKP4Wz5rJWwbtz1IBBjhQ3ZqARFUX4nB7QqcS89lRxG1dAF4tltPxsYXRi3LGNoqlckWhywOB5oEtf/9VsfTdFn3YoOlC5kfi1K3HZINKRvYFUmn0EWuv2BaK0sdP+lNACCMzDLShfR5j6yLrqGvYqRSzcP8bwJfkzQx1q3tfGZEIpC+5anZVGvWoGQbHpLkFJeIrj0vivwp/k9Zzn/x5ymakgJjJBCZOwHiKGYKj4UxgJoey3yypLG5rxILQYF6lpA/of4MFYWMTnPGPxqiqv7exIKuw9LWpNQnvpoCmwmci1GH7hsjhSK7KEMNtyXQk/Sd3lSf4YhMTDBatk9qTOn41KGUai5rUApbca0
  template:
    metadata:
      creationTimestamp: null
      name: awssm-secret
      namespace: default
    type: Opaque
