---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: awssm-secret
  namespace: default
spec:
  encryptedData:
    access-key: AgCqmlgkfbKj3m+VZQe5klfJelTcV7UGzRGbMfogmpdLm+wwUCPihUOqIQnC8/65bHaenvIUDkf7vH4npYYEFRvvCgDD8t9n9m7ejgX4jZFlRKOHC8Et8lXQtNjouuNcoN4ciSEYDDEKaWfhhlxhivsu9l+oe9BwGpADKg4RDG11EBYSl186Sy2S9UBZzlM2uFDwq1IUX4qd5StJiiHObxH7ODXYtj+0ouVMcf4iapyX73MDkcqb5WYRuYvamRMZVPG7NpsKEuruJ7BUCK+OrjtPANTIq8oruJ7YmQLEP+s0RwGynszB4lMA5+RuDP2lqDrV0Q1bbpkVmTQXKnk8dSAvytMIu3Ey6kI01n4J4VLoV5ei6rCAmCtUgl/yqtsje1WZ3n7QYLlkJ28Ye30RoDCSMkP63iZMEw0wftcfswGrfevasDfncoOAdDyNTssqd25POY/ZXdq8S7HGABhv2oADAKHnI5OxYPg7b24PzWKZ8OFskM2C0z0STzJri69s+AmdteYMDUP7ijfmLnv5Heur9XJ0008dVdy1C6DctdfcCcDhMc233AK+aSqS88ks4w2zp+5VArIPBdA3IpGwQr/yo2on2M236+/Mh4X+yBgtA7M3S1Aem83hjzeXomdox1gFrVqRmT+xyjxIdCzzshUoQXF8OUjShyVyKdBlfkwa6QneRR0J7gpyA5TJmzllCajruSbvNh5/BbeZlNVJ4YtLa6moHQ==
    secret-access-key: AgAyuCdcmIf7wxhpQptdUKpZ707mJmMBPHOgrWQpPLQD62NwdE6CfGVyumoa1TVxsDGKatf4+a6Fk9kb92hsieYQnWXc/esa3Wk9IJoRHb579+cuagt3bb0NNXOX+FWJWJlI0BRaM2OGkacEOeWZv4Yx8l5bNVZTSrV4KbdqNGI/TaGenO9weH0r7Z4P627utKtpqY4VBesQp2VO2fwmHC51bofzz46mqIOVyn4t1afFqMxg6kU1NuhLWYPEORCjZmGGx4YZ7glvBCkGV49qVD3R5uPuXSi+7kwadQkxVZQeJD40Tev8xi7fIwLpXVS0m/N2WH2WP+8mb9Aax0dB0ZN57nrOKDzxRTrg/pLhM5TU/O39hQoQEwsJlKL1BLR/a1ljonyLHcoJAquoCmVWtNuQPx07zTgoCRkpyzDo8oWRoVhiB+zN1U70tllsY++ksle/K8KayYa3YcYVdoH1p+YjYbSYZXgawxG1uS5qDOiWuCCio624Qk2tQ9Y1VY2GEFYv3NIsSCCCNI+wiEytaHMRRBn0oHBqe12p5IowskzZhTekQcOuW32Bq8hWVsLW9qWdFDLUowRpIHZO2KMQ+1CAEeZJpoeeBzELxDW+b06jQ4o2YyTsN/dLvB8zDL3VY7F0ZThXP1Swu3VsJPS1kxm3aGXziEXjgaOypso2hH0PPTV2PddvE/U5VkGXfyQ702E5+bhuAtceGmZcnyGhiOOC2C7LkvesEuOlR7edq2ih8Y2bq7kOqMJh
  template:
    metadata:
      creationTimestamp: null
      name: awssm-secret
      namespace: default
    type: Opaque
