apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MYSQL_DATABASE: weatherapp
  MYSQL_USER: admin
  DB_HOST: db #ok
  DB_PORT: "3306" # added
  REDIS_USER: redis #ok
  AUTH_HOST: auth #ok
  AUTH_PORT: "8080" #ok
  WEATHER_PORT: "5000" #ok
  WEATHER_HOST: weather #ok
  REDIS_HOST: redis #ok
